export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";
export const FETCH_ALL_PRODUCTS = "FETCH_ALL_PRODUCTS";
export const SHOW_PROD = "SHOW_PROD";
export const GET_BY_PRODUCT_CAT = "GET_BY_PRODUCT_CAT";
export const GET_BY_PRODUCT_COLOR = "GET_BY_PRODUCT_COLOR";
export const SET_PRICE = "SET_PRICE";

// cart action

export const ADD_TO_CART = "ADD_TO_CART";
export const FETCH_CART = "FETCH_CART";
export const CHANGE_CART = "CHANGE_CART";
